print("hellow, Hi, Hola")
print("my name is tanush")
print("my fev hobbie is playing football")
print("i woke up at 5:00 am")
print("i make notes what i had done today")
print("my birthday is on february 24")
print("sum of 2 + 2 =" ,2 + 2) 
print("multiplycation  of 3 * 9 =", 3*9)
print("suptract of 254 - 359 =", 254 - 359)
print("my fev subject is math and science")
print("i like to spend time with my friends")
print("i like to play roblox")
print("my fev game is also roblox")
